name: travel
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  ionicons: ^0.2.2
  http: ^1.1.0
  google_maps_flutter: ^2.5.3
  url_launcher: ^6.1.14
  flutter_launcher_icons: ^0.13.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"


flutter:
  uses-material-design: true

  assets:
    - assets/places/
    - assets/icons/
    - assets/adilabad/
    - assets/karimnagar/
    - assets/khammam/
    - assets/mahabubnagar/
    - assets/medak/
    - assets/nalgonda/
    - assets/nizamabad/
    - assets/rangareddy/
    - assets/warangal/
    - assets/
 
